# Generated by Django 2.1.7 on 2019-04-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(max_length=30)),
                ('charge_id', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=100)),
                ('dated', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('cin_number', models.CharField(max_length=30, null=True)),
                ('creation_date', models.DateField(null=True)),
                ('modification_date', models.DateField(null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cin_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_status', models.CharField(blank=True, max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=30)),
                ('roc_code', models.CharField(blank=True, max_length=30)),
                ('company_class', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('OPC', 'Private(One Person Company)')], max_length=8)),
                ('listed_type', models.CharField(blank=True, choices=[('Unlisted', 'Unlisted'), ('Listed', 'Listed')], max_length=8)),
                ('company_category', models.CharField(blank=True, max_length=80)),
                ('company_subcategory', models.CharField(blank=True, max_length=80)),
                ('members', models.IntegerField(null=True)),
                ('stock', models.CharField(blank=True, max_length=30)),
                ('email_id', models.EmailField(blank=True, max_length=100)),
                ('authorised_capital', models.IntegerField(null=True)),
                ('paid_capital', models.IntegerField(null=True)),
                ('registered_address', models.TextField()),
                ('other_address', models.TextField(blank=True)),
                ('company_default', models.CharField(choices=[('True', 'YES'), ('False', 'NO')], default='False', max_length=6)),
                ('annual_general_meeting', models.DateField(null=True)),
                ('balancesheet_date', models.DateField(null=True)),
                ('incorporation_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charges', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roc.Charge')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din_pan', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('father_lastname', models.CharField(blank=True, max_length=50)),
                ('cin_number', models.CharField(max_length=30, null=True)),
                ('roc_code', models.CharField(blank=True, max_length=30)),
                ('roc_name', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('designation', models.CharField(blank=True, max_length=30)),
                ('appointment_date', models.DateField(null=True)),
                ('dsc_registered', models.CharField(blank=True, choices=[('True', 'YES'), ('False', 'NO')], max_length=6)),
                ('dsc_expiry_date', models.DateField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('vaild_from', models.DateField(null=True)),
                ('vaild_to', models.DateField(null=True)),
                ('director_default', models.CharField(blank=True, choices=[('True', 'YES'), ('False', 'NO')], max_length=6)),
                ('defaulting_years', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='directors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roc.Director'),
        ),
    ]
