# Generated by Django 2.1.7 on 2019-03-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin_number', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=100)),
                ('roc_code', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=30)),
                ('company_category', models.CharField(max_length=80)),
                ('company_subcategory', models.CharField(max_length=80)),
                ('company_class', models.CharField(max_length=30)),
                ('registered_address', models.CharField(max_length=100)),
                ('listed_type', models.CharField(max_length=100)),
                ('members', models.CharField(max_length=30)),
                ('company_status', models.CharField(max_length=30)),
                ('authorised_capital', models.IntegerField(null=True)),
                ('paid_capital', models.IntegerField(null=True)),
                ('incorporation_date', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
