# Generated by Django 2.1.7 on 2019-03-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_class',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_subcategory',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='company',
            name='incorporation_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='listed_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='members',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='roc_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
