# Generated by Django 2.1.7 on 2019-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0002_auto_20190331_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_class',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('OPC', 'Private(One Person Company)')], max_length=8),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_address',
            field=models.TextField(),
        ),
    ]
