# Generated by Django 2.1.7 on 2019-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0003_auto_20190331_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='listed_type',
            field=models.CharField(blank=True, choices=[('Unlisted', 'Unlisted'), ('Listed', 'Listed')], max_length=8),
        ),
    ]
