# Generated by Django 2.1.7 on 2019-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0005_auto_20190331_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('din', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='directors',
            field=models.ManyToManyField(to='roc.Director'),
        ),
    ]
