# Generated by Django 2.1.7 on 2019-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0006_auto_20190331_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='defaulter',
            field=models.CharField(choices=[('True', 'YES'), ('False', 'NO')], max_length=6, null=True),
        ),
    ]
