# Generated by Django 2.1.7 on 2019-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0007_company_defaulter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='defaulter',
            field=models.CharField(choices=[('True', 'YES'), ('False', 'NO')], default='False', max_length=6),
        ),
    ]
