# Generated by Django 2.1.7 on 2019-03-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0008_auto_20190331_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='defaulter',
            new_name='company_default',
        ),
    ]
