# Generated by Django 2.1.7 on 2019-03-31 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0009_auto_20190331_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srn', models.CharField(max_length=30)),
                ('charge_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('dated', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='directors',
            field=models.ManyToManyField(null=True, to='roc.Director'),
        ),
        migrations.AddField(
            model_name='company',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='roc.Charge'),
        ),
    ]
