# Generated by Django 2.1.7 on 2019-03-31 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roc', '0012_auto_20190331_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='roc_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='director',
            name='roc_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='director',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='director',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='director',
            name='vaild_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='vaild_to',
            field=models.DateField(null=True),
        ),
    ]
